#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <grep_search_parameter> <pod_name_keyword>"
    exit 1
fi

grep_search_parameter="$1"
pod_name_keyword="$2"

kubectl get pods | grep "$pod_name_keyword" | while read -r line; do
    pod_name=$(echo "$line" | awk '{print $1}')
    echo "Pod: $pod_name"
    kubectl logs "$pod_name" | grep "$grep_search_parameter"
    echo "----------------------------------------"
done